/var/spool/slurmd/job4413682/slurm_script: line 13: conda: command not found
r22
Thu Jun 27 01:06:14 PDT 2024
Date and time: 2024-06-27 01:06:15.458391
len_slice  n_select_slc  beams  n_optimization_restarts  output_file
3 2 1 20 best_slices_test.txt
Redshifts:  [0.  0.2 0.5 1.  2.  3. ]
Computing loss function for slice 0
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
