/var/spool/slurmd/job4413659/slurm_script: line 13: conda: command not found
r22
Thu Jun 27 00:40:43 PDT 2024
Date and time: 2024-06-27 00:40:46.251433
len_slice  n_select_slc  beams  n_optimization_restarts  output_file
3 2 1 10 best_slices_test.txt
Redshifts:  [0.  0.2 0.5 1.  2.  3. ]
Computing loss function for slice 0
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
Time now: 2024-06-27 00:41:07.962467
Loss function for slice 0 = 0.05914205996246664
Computing loss function for slice 1
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:243: RuntimeWarning:invalid value encountered in true_divide
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
